title: 'Backcountry Basics'
default_lang: en
author:
  name: 'Nathan Thompson'
  email: matkatnathan@icloud.com
  copyright: 'Copyright 2021 Backcountry Basics. All Rights Reserved.'
taxonomies:
  - category
  - tag
  - featured
metadata:
  description: 'My cool Site'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes:
  /something/else: /blog/sample-3
  /another/one/here: /blog/sample-3
  '/new/*': '/blog/*'
blog:
  route: /blog
logo: BBLogo.png
header:
  title: 'Backcountry Basics'
  description: 'Helping Others Heed the Call of the Wild'
  background: forest.jpg
  # buttons:
  #   -
  #     text: 'Explore!'
  #     url: '#'
  #     class: 'button radius'
social:
  -
    url: 'https://twitter.com/getgrav'
    icon: twitter
  -
    url: '#'
    icon: facebook
  -
    url: 'http://www.vimeo.com'
    icon: vimeo-square
  -
    url: 'http://www.pinterest.com'
    icon: pinterest
footer:
  widget:
    title: 'About Backcountry Basics'
    description: 'Dedicated to helping everyone find or rediscover their passion for enjoying the Great Outdoors by sharing tips, tricks, and insights on a variety of different recreational activities.'
    link: null
copyright: 'Copyright Backcountry Basics© 2021  All Rights Reserved. </a>'
